# Generated by Django 6.0.6 on 2026-06-18 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('pais', models.CharField(max_length=80)),
                ('anio_fundacion', models.PositiveIntegerField()),
                ('sitio_web', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Estudio',
                'verbose_name_plural': 'Estudios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=80)),
                ('plataforma', models.CharField(choices=[('PC', 'PC'), ('PS5', 'PlayStation 5'), ('XBOX', 'Xbox Series'), ('SWITCH', 'Nintendo Switch'), ('MOBILE', 'Movil')], default='PC', max_length=10)),
                ('fecha_lanzamiento', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('calificacion', models.FloatField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videojuegos', to='games.estudio')),
            ],
            options={
                'verbose_name': 'Videojuego',
                'verbose_name_plural': 'Videojuegos',
                'ordering': ['-fecha_lanzamiento'],
            },
        ),
    ]
